# Generated by Django 5.0.1 on 2024-01-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('biography', models.TextField()),
                ('picture', models.ImageField(upload_to='img/autor/')),
                ('active', models.BooleanField(choices=[(True, 'Actif'), (False, 'Inactif')], default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('ARC', 'Architecture'), ('HIST', 'Histoire'), ('ART', 'Art'), ('CUIS', 'Cuisine'), ('ITIN', 'Itineraire')], default='HIST', max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='img/')),
                ('active', models.BooleanField(choices=[(True, 'Actif'), (False, 'Inactif')], default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.autor')),
            ],
        ),
    ]
