# Generated by Django 5.0.1 on 2024-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='active',
            field=models.BooleanField(choices=[(True, 'Actif'), (False, 'Inactif')], default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(default='img/', upload_to='img/'),
            preserve_default=False,
        ),
    ]
