# Generated by Django 5.0.1 on 2024-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_sponsor_active_sponsor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='page',
            field=models.URLField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
