# Generated by Django 5.0.1 on 2024-01-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_sponsor_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
    ]
