# Generated by Django 5.0.1 on 2024-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_autor_author_rename_autor_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
