# Generated by Django 5.0.1 on 2024-01-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_carouselimage_article_itinenaire_article_map_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='itinenaire',
            new_name='itineraire',
        ),
    ]
