# Generated by Django 5.0.1 on 2024-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_itinenaire_article_itineraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='carousel_images',
            field=models.ManyToManyField(blank=True, to='webapp.carouselimage'),
        ),
    ]
