# Generated by Django 5.0.1 on 2024-01-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_article_likes_alter_article_carousel_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('active', models.BooleanField(choices=[(True, 'Actif'), (False, 'Inactif')], default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.article')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.comment')),
            ],
        ),
    ]
