# Generated by Django 5.0.1 on 2024-01-29 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_comment_content_comment_created_at_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='itineraire',
        ),
    ]
