# Generated by Django 5.0.1 on 2024-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_article_itineraire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Article', 'Article'), ('Histoire', 'Histoire'), ('Art', 'Art'), ('Cuisine', 'Cuisine'), ('Itineraire', 'Itineraire')], default='ARTI', max_length=16),
        ),
    ]
