# Generated by Django 5.0.1 on 2024-01-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_eshop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eshop',
            new_name='Product',
        ),
    ]
